# Generated by Django 4.1.13 on 2023-11-25 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='team_logos/'),
        ),
    ]
