# Generated by Django 4.1.13 on 2023-11-26 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cricket_app', '0004_pointstable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PointsTable',
        ),
    ]
